config/routes.rb
Rails.application.routes.draw do
  get 'order_line_items/show'
  get 'order_line_items/new'
  get 'order_line_items/index'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'

  get 'carts/show'

  get "/user/:id", to: "users#show"
  get "/users", to: "users#index"
  get "/user/delete/:id", to: "users#destroy", as: :user_delete_path
  post "create_product", to: "products#create"
  get "/products", to: "products#index"
  get "delete_product/:id", to: "products#destroy", as: :delete_product_path
  post "create_staff", to: "staffs#create"
  get "/staffs", to: "staffs#index"
  get "/admin", to: "staffs#admin"
  get "/create", to: "staffs#new"
  get "delete_staff/:id", to: "staffs#destroy", as: :delete_staff_path
  get "delete/:id", to: "cart_items#destroy", as: :delete_path
  get "/my_orders", to: "orders#show"
  get "/user_order", to: "orders#show"
  get "/carts", to: "carts#show"
  get "/detail", to: "orders#detail"
  get "/details", to: "orders#details"
  get "/order_checkout", to: "order_items#buy_all"
  post "status_update", to: "orders#detail_update"
  

 
  namespace :users do
    get 'root'
  end
  namespace :staffs do
    get 'staff'
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :staffs, path: 'staffs', controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'root', as: :authenticated_root
      end
    end
  end

  devise_scope :staff do
    authenticated :staff do
      namespace :staffs do
        get 'dashboard/index', as: :authenticated_root
      end
    end
  end

  root "products#index"
  resources :users
  resources :products
  resources :staffs
  resources :order_items
  resources :carts
  resources :orders
  resources :cart_items
end

app/models/staff.rb
class Staff < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/staffs/dashboard_controller.rb
class Staffs::DashboardController < ApplicationController
end

app/controllers/staffs/registrations_controller.rb
class Staffs::RegistrationsController < Devise::RegistrationsController
  include Accessible

end

app/controllers/staffs/sessions_controller.rb
# frozen_string_literal: true

class Staffs::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  include Accessible
  skip_before_action :check_resource, only: :destroy
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
before_action :staff_users

  def staff_users
    redirect_to(root_path) if current_staff.nil?
  end
  def index 
    @staffs = Staff.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy
    redirect_to staffs_url 
  end 

  def create
    @staff = Staff.new(staff_params)
    if @staff.save
      flash[:success] = "Staff created"
      redirect_to staffs_path
    else 
      render 'new'
    end
  end

  def show
    @staff = Staff.find(params[:id])
  end

  def edit
    @staff = Staff.find(params[:id])
  end

  def update
    @staff = Staff.find(params[:id])
    if @staff.update(staff_params)
      flash[:success] = "Profile has been updated"
      redirect_to current_staff
    else 
      render "edit"
    end
  end

  def staff_params
    params.require(:staff).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/staffs/dashboard_helper.rb
module Staffs::DashboardHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/admin.html.erb
<div class="admin-container">
  <div class="admin-card">
    <%= link_to "List of All Products", products_path %>
  </div>
  <div class="admin-card">
    <%= link_to "List of All Staff", staffs_path %>
  </div>
  <div class="admin-card">  
    <%= link_to "List of All User", users_path %>
  </div>
  <div class="admin-card">
    <%= link_to "Add Product", new_product_path %>
  </div>
  <% if current_staff.super_admin? %>
    <div class="admin-card">
      <%= link_to "Add Staff", create_path %>
    </div>
  <% end %>
<div>

app/views/staffs/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @staff) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/staffs/index.html.erb
<%= will_paginate @staffs  %>
<div class="user-container">
  <% @staffs.each do |staff| %>
    <div class="user-card">
      <%= link_to staff.name, staff, class: "user-name"%>
      <%= link_to "Delete staff", delete_staff_path_url(id: staff.id), method: :delete, class: "staff-delete-button" %>
    </div>
  <% end %>
</div>

app/views/staffs/new.html.erb
<div class="col">
  <h1>Add a Staff to the team</h1>
  <%= form_with(scope: :staff, url: create_staff_path) do |f| %>

      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "Email" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Password" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %> 
      <%= f.password_field :password_confirmation, class: 'form-control' %> 

    <%= f.submit "Create", class: "btn btn-primary", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/staffs/show.html.erb
<div class="staff-container">
   <p>Hello <%= @staff.name %></p>
   <p>Your email is <%= @staff.email %></p>
   <p>Are you Admin? = <%= @staff.super_admin %></p>
</div>
<div class="staff-button">
   <%= link_to "Edit profile", edit_staff_path(@staff), class: "btn btn-primary"%>
</div>