config/routes.rb
Rails.application.routes.draw do
  get 'order_line_items/show'
  get 'order_line_items/new'
  get 'order_line_items/index'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'

  get 'carts/show'

  get "/user/:id", to: "users#show"
  get "/users", to: "users#index"
  get "/user/delete/:id", to: "users#destroy", as: :user_delete_path
  post "create_product", to: "products#create"
  get "/products", to: "products#index"
  get "delete_product/:id", to: "products#destroy", as: :delete_product_path
  post "create_staff", to: "staffs#create"
  get "/staffs", to: "staffs#index"
  get "/admin", to: "staffs#admin"
  get "/create", to: "staffs#new"
  get "delete_staff/:id", to: "staffs#destroy", as: :delete_staff_path
  get "delete/:id", to: "cart_items#destroy", as: :delete_path
  get "/my_orders", to: "orders#show"
  get "/user_order", to: "orders#show"
  get "/carts", to: "carts#show"
  get "/detail", to: "orders#detail"
  get "/details", to: "orders#details"
  get "/order_checkout", to: "order_items#buy_all"
  post "status_update", to: "orders#detail_update"
  

 
  namespace :users do
    get 'root'
  end
  namespace :staffs do
    get 'staff'
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :staffs, path: 'staffs', controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'root', as: :authenticated_root
      end
    end
  end

  devise_scope :staff do
    authenticated :staff do
      namespace :staffs do
        get 'dashboard/index', as: :authenticated_root
      end
    end
  end

  root "products#index"
  resources :users
  resources :products
  resources :staffs
  resources :order_items
  resources :carts
  resources :orders
  resources :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cart_items
  has_one :cart, dependent: :destroy
  has_one :order, dependent: :destroy
  has_many :order_line_items, through: :order
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
     
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_resource, except: [:destory]
 def create
  @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created"
      sign_in(@user)
      redirect_to @user
    else 
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_resource, only: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :show]


  def logged_in_user 
    unless !current_user.nil? or !current_staff.nil?
      flash[:danger] = "Please Log in"
      redirect_to new_user_session_url
    end
  end
  def show
    @user = User.find(params[:id]) 
  end 

  def index 
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_path
    else 
      redirect_to root
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile has been updated"
      redirect_to current_user
    else 
      render "edit"
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<%= will_paginate @users  %>
<div class="user-container">
  <% @users.each do |user| %>
    <%= link_to user.name, user , class: "user-card"%>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-show-container">
   <p>User name <%= @user.name %></p>
   <p>User email <%= @user.email %></p>
</div>
<% if user_signed_in? %>
   <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-primary" %>
<% elsif staff_signed_in? %>
   <%= link_to "User order", user_order_path(id: @user.id), class: "btn btn-primary" %>
<% end %>