config/routes.rb
Rails.application.routes.draw do
  get 'order_line_items/show'
  get 'order_line_items/new'
  get 'order_line_items/index'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'

  get 'carts/show'

  get "/user/:id", to: "users#show"
  get "/users", to: "users#index"
  get "/user/delete/:id", to: "users#destroy", as: :user_delete_path
  post "create_product", to: "products#create"
  get "/products", to: "products#index"
  get "delete_product/:id", to: "products#destroy", as: :delete_product_path
  post "create_staff", to: "staffs#create"
  get "/staffs", to: "staffs#index"
  get "/admin", to: "staffs#admin"
  get "/create", to: "staffs#new"
  get "delete_staff/:id", to: "staffs#destroy", as: :delete_staff_path
  get "delete/:id", to: "cart_items#destroy", as: :delete_path
  get "/my_orders", to: "orders#show"
  get "/user_order", to: "orders#show"
  get "/carts", to: "carts#show"
  get "/detail", to: "orders#detail"
  get "/details", to: "orders#details"
  get "/order_checkout", to: "order_items#buy_all"
  post "status_update", to: "orders#detail_update"
  

 
  namespace :users do
    get 'root'
  end
  namespace :staffs do
    get 'staff'
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :staffs, path: 'staffs', controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'root', as: :authenticated_root
      end
    end
  end

  devise_scope :staff do
    authenticated :staff do
      namespace :staffs do
        get 'dashboard/index', as: :authenticated_root
      end
    end
  end

  root "products#index"
  resources :users
  resources :products
  resources :staffs
  resources :order_items
  resources :carts
  resources :orders
  resources :cart_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  attr_accessor :item_id
  belongs_to :cart
  belongs_to :product
  has_one :user, through: :cart
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_line_items
  has_many :order_items, through: :order_line_items
  belongs_to :user
end


class Order::Create
  def call(cart)
    Order.transaction do
        cart.destroy
      end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order_line_item
  belongs_to :ordered_product
  has_one :order, through: :order_line_item
  # has_one :user, through: :order_line_items, :source => :order

end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
  has_many :order_items
  has_one :user, through: :order
  belongs_to :order
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  has_one_attached :image
  has_many :order_items
end


class OrderedProduct::Create
  def order(product)
    OrderedProduct.transaction do
      if OrderedProduct.find_by(id: product.id).nil?
        @orderedproduct = OrderedProduct.new(
        id: product.id,
        title: product.title,
        price: product.price,
        description: product.description
        )
        @orderedproduct.save
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  validates :name, presence: true
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cart_items
  has_one :cart, dependent: :destroy
  has_one :order, dependent: :destroy
  has_many :order_line_items, through: :order
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
     
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def user_order(user)
    if Order.find_by(user_id: user[:id]).present?
      Order.find_by(user_id: user[:id])
    else 
      @curr_user = User.find_by(id: user[:id])
      @curr_user.order || @curr_user.build_order
    end
  end
  

  def current_order_line
    if session[:order_line_id].present?
        OrderLineItem.find(session[:order_line_id])
      else
        if !current_order.order_line_items
           current_order.build_order_line_items
        end
        current_order.order_line_items.first
      end
  end


  def current_order
    if session[:order_id].present?
      Order.find(session[:order_id])
    else
      current_user.order || current_user.build_order
    end
  end

  def current_cart
    if session[:cart_id].present?
      Cart.find(session[:cart_id])
    else
      current_user.cart || current_user.build_cart
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goods/edit.html.erb
<h1>Update Good</h1>
<%= form_for(@good) do |g| %>

  <div class="mb-3">
    <%= g.label :title %>
    <%= g.text_field :title, placeholder: "Title"  %>
  </div>

  <div class="mb-3">
    <%= g.label :description %>
    <%= g.text_area :description, placeholder: "Description"  %>
  </div>


  <div class="mb-3">
    <%= g.label :price %>
    <%= g.text_field :price, placeholder: "Price"  %>
  </div>

   <div class="mb-3">
    <%= g.label :image %>
    <%= g.file_field :image %>
  </div>

  <%= g.submit "Save changes", class: "btn btn-primary", class: "btn btn-primary" %>

<% end %>

app/views/goods/index.html.erb
<%= will_paginate @goods %>
<div class="conteiner-good">
  <% @goods.each do |g|  %>
  <div class="item-good">
      <%= link_to g.title, g %>
      <% if g.image.attached? %>
        <%= link_to (image_tag g.image), g %> 
      <% else %>
        <%= link_to (image_tag 'default-imag.jpg'), g %>
      <% end %>
      <p><%= g.price %> $</p>
    </div>
  <% end %>
</div>

app/views/goods/new.html.erb
<%= form_for(:good, url: create_good_path) do |g| %>

<div class="col">
  <h1>Add Item</h1>
  <div class="mb-3">
    <%= g.label :title, class: "form-label" %>
    <%= g.text_field :title, placeholder: "Title", class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div class="mb-3">
    <%= g.label :description, class: "form-label" %>
    <%= g.text_area :description, placeholder: "Description", class: "form-control", id: "exampleFormControlTextarea1"  %>
  </div>


  <div class="mb-3">
    <%= g.label :price, class: "form-label" %>
    <%= g.number_field :price, placeholder: "Price", class: "form-control", id: "exampleFormControlInput1"  %>
  </div>

   <div class="mb-3">
    <%= g.label :image, class: "form-label" %>
    <%= g.file_field :image, class: "form-control form-control-sm", id: "formFileSm", type: "file" %>
  </div>

  <%= g.submit "Save changes", class: "btn btn-primary", class: "btn btn-primary" %>
</div>
<% end %>

app/views/header/_header.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="p-2">
        <%= link_to "Home", root_path %>
      </div>

        <% if user_signed_in? %> 
        <div class="ml-auto p-2">
              <%= link_to "My cart", carts_path %> 
          </div>
          <div class="p-2">
              <%= link_to "My orders", my_orders_path %> 
          </div>
            <div class="p-2">
              <%= link_to "Products", products_path %> 
          </div>
          <div class="p-2">
              <%= link_to "Profile", current_user %>  |
          </div>
          <div class="p-2">
            <%= link_to "Sign out", destroy_user_session_path %>
          </div>

        <% elsif staff_signed_in? %>
                  
          <div class="ml-auto p-2">
            <%= link_to "Admin Panel", admin_path %>
          </div> 
          <div class="p-2">
            <%= link_to "Profile", current_staff%> |
          </div> 
          <div class="p-2">
            <%= link_to 'Sign Out as Admin', destroy_staff_session_path, method: :delete %> 
          </div>
          
        <% else !user_signed_in? %>

          <div class="ml-auto p-2">
            <%= link_to "Sing in", new_user_session_path %>
          </div>
          <div class="p-2">
            <%= link_to "Sign up", new_user_registration_path %> |
          </div>  
          <div class="p-2">
            <%= link_to "Sign In as Admin", new_staff_session_path %> 
          </div>
        <% end %> 

    </nav>

app/views/shared/_flash.html.erb
<!--
* File: app/views/shared/_flash.html.erb
* Note: the `html_safe` is important here
-->

<% flash.each do |type, msg| %>
    <div class="alert alert-info">
        <%= msg.html_safe %>
    </div>
<% end %>