config/routes.rb
Rails.application.routes.draw do
  get 'order_line_items/show'
  get 'order_line_items/new'
  get 'order_line_items/index'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'

  get 'carts/show'

  get "/user/:id", to: "users#show"
  get "/users", to: "users#index"
  get "/user/delete/:id", to: "users#destroy", as: :user_delete_path
  post "create_product", to: "products#create"
  get "/products", to: "products#index"
  get "delete_product/:id", to: "products#destroy", as: :delete_product_path
  post "create_staff", to: "staffs#create"
  get "/staffs", to: "staffs#index"
  get "/admin", to: "staffs#admin"
  get "/create", to: "staffs#new"
  get "delete_staff/:id", to: "staffs#destroy", as: :delete_staff_path
  get "delete/:id", to: "cart_items#destroy", as: :delete_path
  get "/my_orders", to: "orders#show"
  get "/user_order", to: "orders#show"
  get "/carts", to: "carts#show"
  get "/detail", to: "orders#detail"
  get "/details", to: "orders#details"
  get "/order_checkout", to: "order_items#buy_all"
  post "status_update", to: "orders#detail_update"
  

 
  namespace :users do
    get 'root'
  end
  namespace :staffs do
    get 'staff'
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :staffs, path: 'staffs', controllers: {
    sessions: 'staffs/sessions',
    registrations: 'staffs/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'root', as: :authenticated_root
      end
    end
  end

  devise_scope :staff do
    authenticated :staff do
      namespace :staffs do
        get 'dashboard/index', as: :authenticated_root
      end
    end
  end

  root "products#index"
  resources :users
  resources :products
  resources :staffs
  resources :order_items
  resources :carts
  resources :orders
  resources :cart_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  attr_accessor :item_id
  belongs_to :cart
  belongs_to :product
  has_one :user, through: :cart
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_line_items
  has_many :order_items, through: :order_line_items
  belongs_to :user
end


class Order::Create
  def call(cart)
    Order.transaction do
        cart.destroy
      end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order_line_item
  belongs_to :ordered_product
  has_one :order, through: :order_line_item
  # has_one :user, through: :order_line_items, :source => :order

end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
  has_many :order_items
  has_one :user, through: :order
  belongs_to :order
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  has_one_attached :image
  has_many :order_items
end


class OrderedProduct::Create
  def order(product)
    OrderedProduct.transaction do
      if OrderedProduct.find_by(id: product.id).nil?
        @orderedproduct = OrderedProduct.new(
        id: product.id,
        title: product.title,
        price: product.price,
        description: product.description
        )
        @orderedproduct.save
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  validates :name, presence: true
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cart_items
  has_one :cart, dependent: :destroy
  has_one :order, dependent: :destroy
  has_many :order_line_items, through: :order
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
     
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :user

  def user
    redirect_to(root_path) if current_user.nil?
  end

  def index
  end

  def show
    # byebug
    @cart_items = current_cart.cart_items
    @order_line_item = current_order.order_line_items.new
    @order_item = @order_line_item.order_items.new
  end

  def new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_staff!, except: [:index, :show]


  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def new 
    @product = Product.new 
  end


  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(products_params)
      flash[:success] = "Updated"
      redirect_to @product
    else 
      render "edit"
    end
  end 

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = "Product deleted"
    redirect_to products_path
  end 
  
  def show
    @product = Product.find(params[:id])
    if user_signed_in? 
      @cart_item = current_cart.cart_items.new
    end
  end

  def index 
    @products = Product.paginate(page: params[:page], per_page: 12)
  end

  def products_params
    params.require(:product).permit(:title, :description, :price, :image)
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :show]


  def logged_in_user 
    unless !current_user.nil? or !current_staff.nil?
      flash[:danger] = "Please Log in"
      redirect_to new_user_session_url
    end
  end
  def show
    @user = User.find(params[:id]) 
  end 

  def index 
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_path
    else 
      redirect_to root
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile has been updated"
      redirect_to current_user
    else 
      render "edit"
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def user_order(user)
    if Order.find_by(user_id: user[:id]).present?
      Order.find_by(user_id: user[:id])
    else 
      @curr_user = User.find_by(id: user[:id])
      @curr_user.order || @curr_user.build_order
    end
  end
  

  def current_order_line
    if session[:order_line_id].present?
        OrderLineItem.find(session[:order_line_id])
      else
        if !current_order.order_line_items
           current_order.build_order_line_items
        end
        current_order.order_line_items.first
      end
  end


  def current_order
    if session[:order_id].present?
      Order.find(session[:order_id])
    else
      current_user.order || current_user.build_order
    end
  end

  def current_cart
    if session[:cart_id].present?
      Cart.find(session[:cart_id])
    else
      current_user.cart || current_user.build_cart
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/edit.html.erb
<h1>Update product</h1>
<%= form_with(model: @product) do |g| %>

  <%= g.hidden_field :id, :value => @product.id * 2 + 1 %>

  <div class="mb-3">
    <%= g.label :title %>
    <%= g.text_field :title, placeholder: "Title"  %>
  </div>

  <div class="mb-3">
    <%= g.label :description %>
    <%= g.text_area :description, placeholder: "Description"  %>
  </div>


  <div class="mb-3">
    <%= g.label :price %>
    <%= g.text_field :price, placeholder: "Price"  %>
  </div>

   <div class="mb-3">
    <%= g.label :image %>
    <%= g.file_field :image %>
  </div>

  <%= g.submit "Save changes", class: "btn btn-primary", class: "btn btn-primary" %>

<% end %>

app/views/products/index.html.erb
<%= will_paginate @products, class: "pagination"%>
<div class="container-products">
  <% @products.each do |g|  %>
    <div class="item-product">
        <a href=<%= "/products/#{g.id}"%> class="product-img-container">
          <%= image_tag (g.image.attached?  ? g.image : 'default-imag.jpg'), class: "product-img" %> 
        </a>
        <p class="product-title"><%= g.title %></p>
        <p class="product-price">Tax is not included <%= g.price %> $</p>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%= form_with(scope: :product, url: create_product_path) do |g| %>

<div class="col">
  <h1>Add Product</h1>
  <div class="mb-3">
    <%= g.label :title, class: "form-label" %>
    <%= g.text_field :title, placeholder: "Title", class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div class="mb-3">
    <%= g.label :description, class: "form-label" %>
    <%= g.text_area :description, placeholder: "Description", class: "form-control", id: "exampleFormControlTextarea1"  %>
  </div>


  <div class="mb-3">
    <%= g.label :price, class: "form-label" %>
    <%= g.number_field :price, placeholder: "Price", class: "form-control", id: "exampleFormControlInput1"  %>
  </div>

   <div class="mb-3">
    <%= g.label :image, class: "form-label" %>
    <%= g.file_field :image, class: "form-control form-control-sm", id: "formFileSm", type: "file" %>
  </div>

  <%= g.submit "Save changes", class: "btn btn-primary", class: "btn btn-primary" %>
</div>
<% end %>

app/views/products/show.html.erb
<div class="product-info-container">
  <%= image_tag (@product.image.attached? ? @product.image : 'default-imag.jpg'),  class: "product-info-img" %>
  <div class="product-info">
    <div class="product-info-title">
      <%= @product.title %>
    </div>
    <div class="product-info-description">
      <%= @product.description %>
    </div>
    
    <div class="product-info-button-container">
      <% if staff_signed_in? %>
        <%= link_to "Edit", edit_product_path(@product), class: "product-info-admin-button" %>
        <%= link_to "Delete", delete_product_path_url(@product), class: "product-info-admin-button" %>
      <% else %>

        <%= form_with model: @cart_item, remote: true, class: "product-info-form-button" do |f|%>
          <%= f.hidden_field :product_id, :value => @product.id %>
          <%= f.submit "Add to Card ",  class: "product-info-button" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>